create extension if not exists pgcrypto;

create table if not exists public.players (
    id uuid primary key default gen_random_uuid(),
    gamertag text not null,
    gamertag_key text not null unique,
    balance integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create or replace function public.set_players_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists set_players_updated_at on public.players;

create trigger set_players_updated_at
before update on public.players
for each row
execute function public.set_players_updated_at();

alter table public.players enable row level security;

drop policy if exists "players can be read" on public.players;
create policy "players can be read"
on public.players
for select
to anon
using (true);

drop policy if exists "players can be created" on public.players;
create policy "players can be created"
on public.players
for insert
to anon
with check (true);

drop policy if exists "players can update balances" on public.players;
create policy "players can update balances"
on public.players
for update
to anon
using (true)
with check (true);

create table if not exists public.feedback (
    id bigint generated by default as identity primary key,
    player_id uuid,
    gamertag text,
    type text not null,
    message text not null,
    category text,
    difficulty text,
    score integer,
    round_money integer,
    opponent_money integer,
    balance_after_round integer,
    page_url text,
    user_agent text,
    created_at timestamptz not null default now()
);

alter table public.feedback enable row level security;

drop policy if exists "feedback can be created" on public.feedback;
create policy "feedback can be created"
on public.feedback
for insert
to anon
with check (true);
